from datetime import datetime
from typing import Optional

from pydantic import BaseModel, EmailStr, Field


class RegisterIn(BaseModel):

    email: EmailStr

    password: str = Field(min_length=6, max_length=128)

    name: Optional[str] = None


class LoginIn(BaseModel):

    email: EmailStr

    password: str


class ForgotIn(BaseModel):

    email: EmailStr


class GuestIn(BaseModel):
    """Start (or resume) an account with no registration.

    `device_id` is generated by the app and kept in the device keychain. It is
    not a fingerprint and identifies nothing about the person — its only job
    is to make the free FX grant happen once per installation instead of once
    per app launch.
    """

    device_id: str = Field(min_length=8, max_length=128)


class GoogleSessionIn(BaseModel):

    session_id: str

class GoogleLoginIn(BaseModel):

    token: str


class AppleLoginIn(BaseModel):

    # Identity token from the native Sign in with Apple flow.
    token: str

    # Apple gives the display name to the CLIENT on the first sign-in only,
    # and never puts it in the token — so the app forwards it here.
    full_name: Optional[str] = Field(default=None, max_length=120)


class UserOut(BaseModel):

    user_id: str

    # Empty for a guest: the address on a guest document is a synthetic
    # placeholder that exists only to satisfy the unique index, and no screen
    # should ever print it.
    email: str

    name: Optional[str] = None

    picture: Optional[str] = None

    provider: str

    # True until the account gains a password, a Google identity or an Apple
    # identity. The app uses it to decide when to ask for a sign-up.
    is_guest: bool = False

    is_premium: bool = False

    premium_tier: Optional[str] = None

    # When the current subscription period ends. Null for a lifetime purchase
    # or an account that has never subscribed.
    premium_expires_at: Optional[datetime] = None

    # True while the subscription is set to charge again. False after the user
    # turns auto-renew off in the store — they keep access until the date
    # above, so the two fields together are the difference between "renews on"
    # and "ends on", which is what a subscriber actually wants to know.
    premium_auto_renew: bool = False

    # Legacy fields kept for backward compatibility.
    free_credits_used: int = 0
    free_credits_total: int = 1

    # Current PrankFX balance.
    fx_credits: int = 0

    created_at: datetime


class AuthResponse(BaseModel):

    token: str

    user: UserOut